// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9yCr1-cxIPloPotkaCqpTFtMK9vnxezE',
    appId: '1:759657039101:web:d7a04615ed3dc3cbb06a94',
    messagingSenderId: '759657039101',
    projectId: 'nearvibe-916ef',
    authDomain: 'nearvibe-916ef.firebaseapp.com',
    storageBucket: 'nearvibe-916ef.firebasestorage.app',
    measurementId: 'G-C5KEDP48L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCodFc71XwTxUeenEP74sYROghaPek2W3c',
    appId: '1:759657039101:android:792ac8be7945e867b06a94',
    messagingSenderId: '759657039101',
    projectId: 'nearvibe-916ef',
    storageBucket: 'nearvibe-916ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoP1TVhu333WBuDl4b-gPl6wPUMMojaP8',
    appId: '1:759657039101:ios:32cb6dba06d985e2b06a94',
    messagingSenderId: '759657039101',
    projectId: 'nearvibe-916ef',
    storageBucket: 'nearvibe-916ef.firebasestorage.app',
    iosBundleId: 'com.example.nearVibe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoP1TVhu333WBuDl4b-gPl6wPUMMojaP8',
    appId: '1:759657039101:ios:32cb6dba06d985e2b06a94',
    messagingSenderId: '759657039101',
    projectId: 'nearvibe-916ef',
    storageBucket: 'nearvibe-916ef.firebasestorage.app',
    iosBundleId: 'com.example.nearVibe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9yCr1-cxIPloPotkaCqpTFtMK9vnxezE',
    appId: '1:759657039101:web:04b973739cd970afb06a94',
    messagingSenderId: '759657039101',
    projectId: 'nearvibe-916ef',
    authDomain: 'nearvibe-916ef.firebaseapp.com',
    storageBucket: 'nearvibe-916ef.firebasestorage.app',
    measurementId: 'G-2KSM5MC1KX',
  );
}
